### PR TITLE
Fix Chat Welcome Messages

### LINKED ISSUE #1667: [Bug] Welcome message does not work
Grasscutter version: 1.2.3-dev-14a7dd9
New resources
Welcome message does not work
This function seems to have occurred after 1.2.3 and has not been repaired for a long time
Grasscutter 版本：1.2.3-dev-14a7dd9
新的resources
config中的Welcome message不起作用
此问题在1.2.3之后貌似就长期出现了，并且未修复

### PR DESCRIPTION
**Pull request by GanyusLeftHorn**
## Description

This PR fixes the issue of server welcome messages not showing in the chat history.

## Issues fixed by this PR

Fixes #1667

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

File: src/main/java/emu/grasscutter/game/chat/ChatSystem.java [hunk 1]
```diff
@@ -50,15 +50,15 @@ private boolean tryInvokeCommand(Player sender, Player target, String rawMessage
...
             this.history.put(uid, new HashMap<>());
         }
-        if (!this.history.get(uid).containsKey(targetId)) {
-            this.history.get(uid).put(targetId, new ArrayList<>());
+        if (!this.history.get(uid).containsKey(partnerId)) {
+            this.history.get(uid).put(partnerId, new ArrayList<>());
         }
 
-        this.history.get(uid).get(targetId).add(info);
+        this.history.get(uid).get(partnerId).add(info);
```
Comment (Birdulon) [inline src/main/java/emu/grasscutter/game/chat/ChatSystem.java:61]:
```suggestion
        this.history.computeIfAbsent(uid, HashMap::new)
                    .computeIfAbsent(partnerId, ArrayList::new)
                    .add(info);
```

File: src/main/java/emu/grasscutter/game/chat/ChatSystem.java [hunk 2]
```diff
@@ -67,27 +67,27 @@ public void clearHistoryOnLogout(Player player) {
...
-    public void handlePullPrivateChatReq(Player player, int targetUid) {
-        if (this.history.containsKey(player.getUid()) && this.history.get(player.getUid()).containsKey(targetUid)) {
-            player.sendPacket(new PacketPullPrivateChatRsp(this.history.get(player.getUid()).get(targetUid)));
+    public void handlePullPrivateChatReq(Player player, int partnerId) {
+        if (this.history.getOrDefault(player.getUid(), Map.of()).containsKey(partnerId)) {
+            player.sendPacket(new PacketPullPrivateChatRsp(this.history.get(player.getUid()).get(partnerId)));
         }
         else {
             player.sendPacket(new PacketPullPrivateChatRsp(List.of()));
         }
```
Comment (Birdulon) [inline src/main/java/emu/grasscutter/game/chat/ChatSystem.java:76]:
```suggestion
        var chatHistory = this.history.computeIfAbsent(player.getUid(), HashMap::new)
                                .computeIfAbsent(partnerId, ArrayList::new);
        player.sendPacket(new PacketPullPrivateChatRsp(chatHistory));
```

File: src/main/java/emu/grasscutter/game/chat/ChatSystem.java [hunk 3]
```diff
@@ -67,27 +67,27 @@ public void clearHistoryOnLogout(Player player) {
...
     }
 
     public void handlePullRecentChatReq(Player player) {
+        // If this user has no chat history yet, create it by sending the server welcome messages.
+        if (!this.history.getOrDefault(player.getUid(), Map.of()).containsKey(GameConstants.SERVER_CONSOLE_UID)) {
```
Comment (Birdulon) [inline src/main/java/emu/grasscutter/game/chat/ChatSystem.java:81]:
```suggestion
        if (!this.history.computeIfAbsent(player.getUid(), HashMap::new).containsKey(GameConstants.SERVER_CONSOLE_UID)) {
```

**Review by Birdulon — APPROVED** [review]

File: src/main/java/emu/grasscutter/game/chat/ChatSystem.java (hunk 2 above)
Comment (Birdulon) [reply src/main/java/emu/grasscutter/game/chat/ChatSystem.java:76]: Not sure if applying this directly from web interface is dangerous since it bypassed a UI restriction
image
