### PR TITLE
Fix receiving reward repeatedly

### LINKED ISSUE #1105: [Bug] 严重回档bug和无限发送领取请求
在多人反馈下，一些操作后似乎将造成无法存档。
主要反馈是说在神像回血数次后，将触发（并未100%确定）
---
此外，在一些领取界面：邮件、冒险奖励等地方，可以通过限制网速等方式来无限请求领取。

### PR DESCRIPTION
**Pull request by zhaodice**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
fix #1105 （just fix "无限发送领取请求"）

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

File: src/main/java/emu/grasscutter/server/packet/recv/HandlerTakePlayerLevelRewardReq.java [hunk 1]
```diff
@@ -1,40 +1,39 @@
...
     public void handle(GameSession session, byte[] header, byte[] payload) throws Exception {
-        TakePlayerLevelRewardReq req = TakePlayerLevelRewardReq.parseFrom(payload);
-
-        int level = req.getLevel();
-        int rewardId = GameData.getPlayerLevelDataMap().get(level).getRewardId();
-
-        if (rewardId != 0) {
-            List<ItemParamData> rewardItems = GameData.getRewardDataMap().get(rewardId).getRewardItemList();
-            session.getPlayer().getInventory().addItemParamDatas(rewardItems, ActionReason.PlayerUpgradeReward);
+        synchronized (HandlerTakePlayerLevelRewardReq.class) {
```
Comment (ghost) [inline src/main/java/emu/grasscutter/server/packet/recv/HandlerTakePlayerLevelRewardReq.java]: You only need to synchronize the player object, not the class itself.

File: src/main/java/emu/grasscutter/server/packet/recv/HandlerTakePlayerLevelRewardReq.java [hunk 2]
```diff
@@ -1,40 +1,39 @@
...
-            session.getPlayer().setRewardedLevels(rewardedLevels);
+            if (!rewardedLevels.contains(level)) {// No duplicated reward
+                int rewardId = GameData.getPlayerLevelDataMap().get(level).getRewardId();
+                if (rewardId != 0) {
+                    List<ItemParamData> rewardItems = GameData.getRewardDataMap().get(rewardId).getRewardItemList();
+                    pl.getInventory().addItemParamDatas(rewardItems, ActionReason.PlayerUpgradeReward);
+                    rewardedLevels.add(level);
+                    pl.setRewardedLevels(rewardedLevels);
+                    session.send(new PacketTakePlayerLevelRewardRsp(level, rewardId));
+                }
```
Comment (ghost) [inline src/main/java/emu/grasscutter/server/packet/recv/HandlerTakePlayerLevelRewardReq.java:36]: If you want to be extra safe, you can save the player to the database (`pl.save()`) after youre done.

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by ghost — APPROVED** [review]
